packages:
  - apps/*
  - packages/*
blockExoticSubdeps: true
trustPolicy: no-downgrade
minimumReleaseAge: "14400"
catalogMode: strict
catalog:
  # ======================
  # Core runtime (React)
  # ======================
  react: "19.0.0"
  react-dom: "19.0.0"
  react-router: "^7.3.0"
  react-router-dom: "^7.4.0"
  "@types/react": "^19.0.10"
  "@types/react-dom": "^19.0.0"

  # ======================
  # State / UI utilities
  # ======================
  class-variance-authority: "^0.7.1"
  clsx: "^2.1.1"
  cmdk: "^1.1.1"
  lucide-react: "^0.483.0"
  tailwind-merge: "^3.0.2"
  zustand: "^5.0.3"

  # ======================
  # Radix UI
  # ======================
  "@radix-ui/react-checkbox": "^1.1.4"
  "@radix-ui/react-collapsible": "^1.1.3"
  "@radix-ui/react-context-menu": "^2.2.6"
  "@radix-ui/react-dialog": "^1.1.6"
  "@radix-ui/react-dropdown-menu": "^2.1.6"
  "@radix-ui/react-label": "^2.1.4"
  "@radix-ui/react-navigation-menu": "^1.2.5"
  "@radix-ui/react-popover": "^1.1.11"
  "@radix-ui/react-progress": "^1.1.4"
  "@radix-ui/react-radio-group": "^1.3.4"
  "@radix-ui/react-scroll-area": "^1.2.3"
  "@radix-ui/react-select": "^2.1.6"
  "@radix-ui/react-separator": "^1.1.2"
  "@radix-ui/react-slider": "^1.2.3"
  "@radix-ui/react-slot": "^1.2.0"
  "@radix-ui/react-switch": "^1.2.2"
  "@radix-ui/react-tabs": "^1.1.9"
  "@radix-ui/react-tooltip": "^1.1.8"

  # ======================
  # Backend / API
  # ======================
  "@aws-sdk/client-s3": "^3.946.0"
  "@aws-sdk/s3-request-presigner": "^3.946.0"
  "@prisma/client": "^6.7.0"
  prisma: "^6.7.0"
  cors: "^2.8.5"
  "@types/node": "^22.13.10"
  express: "^4.19.2"
  express-openid-connect: "^2.17.1"
  express-rate-limit: "^7.5.1"

  # ======================
  # Tooling / Build
  # ======================
  "@babel/preset-env": "^7.28.3"
  "@babel/preset-react": "^7.27.1"
  "@babel/preset-typescript": "^7.27.1"
  "@eslint/js": "^9.25.0"
  "@vitejs/plugin-react": "^4.3.4"
  eslint: "^9.25.0"
  globals: "^15.15.0"
  typescript: "~5.8.3"
  vite: "^6.2.0"

  # ======================
  # Testing
  # ======================
  "@testing-library/react": "^16.3.0"
  "@types/jest": "^29.5.12"
  jest: "^29.2.1"
  jest-environment-jsdom: "^30.2.0"
  vitest: "^3.2.4"
  "@vitest/browser": "^3.2.4"
  "@vitest/coverage-v8": "^3.2.4"
  playwright: "^1.56.1"

  # ======================
  # Storybook
  # ======================
  "@chromatic-com/storybook": "4.1.1"
  "@storybook/addon-a11y": "9.1.17"
  "@storybook/addon-docs": "9.1.17"
  "@storybook/addon-vitest": "9.1.17"
  "@storybook/react-vite": "9.1.17"
  "@storybook/test": "8.6.14"
  eslint-plugin-storybook: "9.1.17"
  storybook: "9.1.17"

  # ======================
  # TBD
  # ======================
  "@huggingface/transformers": "^3.7.6"
  "@mdx-js/react": "^3.1.0"
  "@mdx-js/rollup": "^3.1.0"
  "@tailwindcss/typography": "^0.5.16"
  "@tailwindcss/vite": "^4.1.4"
  concurrently: "^9.1.2"
  "@wavesurfer/react": "^1.0.11"
  d3: "^7.9.0"
  d3-sankey: "^0.12.3"
  posthog-js: "^1.255.1"
  prop-types: "^15.8.1"
  react-force-graph-2d: "^1.27.1"
  react-lite-youtube-embed: "^2.5.1"
  react-markdown: "^10.1.0"
  react-resizable-panels: "^2.1.7"
  recharts: "^3.1.2"
  remark-gfm: "^4.0.1"
  tailwindcss: "^4.0.14"
  tailwindcss-animate: "^1.0.7"
  wavesurfer.js: "^7.11.1"
  eslint-plugin-react-hooks: "^5.1.0"
  eslint-plugin-react-refresh: "^0.4.19"
  typescript-eslint: "^8.24.1"
