name: "🧭 Area"
description: "Collect similar tasks/features/bugs into an area/umbrella issue"
type: "area-umbrella-issue"
assignees: will-rosenberg
projects: "SimpleAmericanAccent/9"
body:
  - type: markdown
    attributes:
      value: "Optional description, save, then add sub-issues."
  - type: textarea
    attributes:
      label: Description (optional)
