name: "Bug report"
description: "Report a problem with the SAA App. Please provide enough information that we can reproduce the problem."
type: "bug"
body:
- type: textarea
  attributes:
    label: What did you expect to happen?
    render: shell
  validations:
    required: true
- type: textarea
  attributes:
    label: What happened instead?
    render: shell
  validations:
    required: true
- type: textarea
  attributes:
    label: What steps need to be taken to reproduce the bug?
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else you want to share?
