name: "📈 Epic"
description: "A big project made of smaller issues."
assignees: will-rosenberg
projects: "SimpleAmericanAccent/9"
body:
- type: input
  attributes:
    label: What's it about?
  validations:
    required: true
- type: input
  attributes:
    label: Why is it worth doing?
  validations:
    required: true
- type: textarea
  attributes:
    label: What smaller issues are part of this?
  validations:
    required: true
- type: textarea
  attributes:
    label: What must be true for this Epic to be complete?
  validation:
    required: true
