name: "💡 Feature request"
description: "Suggest a feature for the SAA App."
type: "feature"
assignees: will-rosenberg
projects: "SimpleAmericanAccent/9"
body:
- type: input
  attributes:
    label: Is your feature request related to a problem? Please describe.
  validations:
    required: true
- type: input
  attributes:
    label: Describe the solution you'd like
  validations:
    required: true
- type: input
  attributes:
    label: Describe alternatives you've considered
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else you want to share?
